version: '3'

services:
  ubuntu22.04:
    container_name: 'ubuntu22.04'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=$USERNAME
        - PASSWORD=$PASSWORD
    volumes:
      - ./work:/home/$USERNAME/work
    tty: true
    working_dir: /home/$USERNAME
